### ISSUE TITLE
IT can't compile In the openjdk environment, how can i solve this problem? thanks.

### ISSUE THREAD

**Issue by jalenchen0214** [scanoss/scanner.java#1]
the following crc32c can not be compile:
    private static long crc32c(String s) {
        Crc32c checksum = new Crc32c();
        checksum.update(s.getBytes(), 0, s.length());
        return checksum.getValue();
    }

    private static String crc32cHex(long l) {
        Checksum checksum = new Crc32c();
        checksum.update(toLittleEndian(l), 0, toLittleEndian(l).length);
        return zeroPaddedString(Long.toHexString(checksum.getValue()));
    }

**Comment by eeisegn** [comment]
Hi,

This sample project code is deprecated and no longer being maintained. If you're looking for an up-to-date API implementation, please look at the Python implementation: [https://github.com/scanoss/scanoss.py](https://github.com/scanoss/scanoss.py).

Thanks, Scanoss.
