### ISSUE TITLE
ScanOSS for Java 

### ISSUE THREAD

**Issue by garavsoni1234** [scanoss/scanner.java#5]
We are currently using Java for our SonarQube application. We are manually trying to integrate the ScanOSS CLI into our application using a plugin. Can we use the deprecated version of the CLI for JAVA for our plugin? Is there a better way to integrate python cli into Java? What is the best route for us? 

Please let me know.

Thank you!

**Comment by scanoss-cs** [comment]
Hi,

We are investigating and will get back to you shortly...

SCANOSS

**Comment by scanoss-cs** [comment]
Hi,

Based on our offline conversation we have agreed that it's better to leverage the CLI integration (calling it from Java).

Thanks! SCANOSS
